# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np

In [6]:
arr=np.random.random((3,3,3))
arr

array([[[0.08625281, 0.65927884, 0.64835002],
        [0.41666922, 0.93091005, 0.39719038],
        [0.32660922, 0.8903293 , 0.27146257]],

       [[0.33592349, 0.75541782, 0.17372612],
        [0.80959154, 0.35317084, 0.48726873],
        [0.3121846 , 0.58070623, 0.77561224]],

       [[0.10812318, 0.87431888, 0.33844179],
        [0.68936828, 0.53563849, 0.49964305],
        [0.92638932, 0.42317975, 0.71319016]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
x=np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
x=np.ones((3,3))
print("Checkboard Pattern:")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

Checkboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [15]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[0.25273427, 0.68904302, 0.7807761 , 0.47012005, 0.3409514 ],
       [0.71547972, 0.97016061, 0.76418364, 0.85986744, 1.        ],
       [0.48295589, 0.82183978, 0.96843177, 0.31266823, 0.34874715],
       [0.44500354, 0.        , 0.74800871, 0.68266214, 0.25312756],
       [0.15629531, 0.65904401, 0.96833128, 0.52932892, 0.15909501]])

# 5.  How to find common values between two arrays?

In [16]:
arr1=np.array([10,14,15,20,40])
arr2=np.array([10,40,50,60,70])
common=np.intersect1d(arr1,arr2)
common

array([10, 40])

# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [18]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 0 0 0 0]
Second array:
[0 0 0 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [20]:
X = np.random.random(10)
X[X.argmax()] = 0
print(X)

[0.         0.18274708 0.19975485 0.75297947 0.16952881 0.80240686
 0.79270203 0.11504583 0.07805902 0.4138698 ]


9. How to print all the values of an array?

In [22]:
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [25]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
Y


array([[-0.12257642, -0.15702421, -0.03637028,  0.43465267, -0.0518513 ,
        -0.38721953, -0.34328157,  0.47121676,  0.51242552, -0.31997164],
       [ 0.19690965, -0.04230018,  0.06569375, -0.3476895 , -0.29459353,
        -0.18810614,  0.26687587, -0.23908768,  0.32984947,  0.25244829],
       [-0.32934065, -0.18535636, -0.00611949,  0.02812426,  0.22955598,
        -0.10111948, -0.06380476,  0.24548496, -0.22054317,  0.40311872],
       [-0.27471082,  0.01087454,  0.27218079,  0.15297912, -0.38878239,
        -0.04925432,  0.39459265,  0.37148752, -0.20444865, -0.28491843],
       [-0.30481337,  0.36503805,  0.01473251,  0.27556627,  0.04803981,
         0.00343636, -0.03929107,  0.07888951, -0.21624179, -0.22535629]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [26]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

[3. 3. 1. 4. 4. 4. 4. 3. 1. 3.]


# 12.How to get the diagonal of a dot product?

In [28]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))

array([27, 60, 36])

# 13.How to find the most frequent value in an array?

In [30]:
Z = np.random.randint(10,20,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[11 17 16 13 15 15 17 19 13 12 19 19 13 19 15 11 18 13 13 12 17 13 11 12
 17 14 16 12 10 15 12 17 13 19 10 18 13 17 17 10 14 14 14 10 12 18 18 14
 14 14]
rank: 13


# 14.How to get the n largest values of an array

In [31]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [33]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])